### ISSUE TITLE
App returns "Required flags "user, blog, filename" not set when they are provided on the command line

### ISSUE THREAD

**Issue by rcampoamor** [writeas/wp-import#3]
Trying to run the tool with 

./wpimport import --user foo --blog bar --filename wpstuff.xml

Which always returns "Required flags "user, blog, filename" not set"

Running on ubuntu and go 1.22.2 linux/amd64

Suggestions?

**Comment by thebaer** [comment]
Thanks for reporting this! It does look like there was a bug here, and I've fixed that in #4. I'll merge that, and then if you pull in the latest changes and build again it should work.

**Comment by rcampoamor** [comment]
Hmmm, re-cloned and rebuilt, still getting the same error...

**Comment by thebaer** [comment]
Are you sure you rebuilt it correctly like this (from the project directory)?

```
go build ./cmd/wpimport/
```

When I ran the exact example you gave, I got this output:

```
$ ./wpimport import --user foo --blog bar --filename wpstuff.xml
Hello foo
Please enter your password:

```

**Comment by rcampoamor** [comment]
Disregard - I was in the wrong darn clone directory. Sorry for the confusion

**Comment by rcampoamor** [comment]
It logs in but generates a different sort of error and then I think it blocks me:

2025/02/20 17:01:50 Reading mobrec.xml...
2025/02/20 17:01:50 Parsing...
2025/02/20 17:01:50 Found 1 channels.
2025/02/20 17:01:50 Channel: moebius recursive
2025/02/20 17:01:50 Found 788 items.
2025/02/20 17:01:50 Creating The Scourge of Subdivisions
2025/02/20 17:01:50 Creating Newton, Palm and PSP
2025/02/20 17:01:50 Creating Book: Buying a Fishing Rod for My Grandfather
create post: invalid character '<' looking for beginning of value
2025/02/20 17:01:50 Creating On the pond
create post: invalid character '<' looking for beginning of value
2025/02/20 17:01:50 Creating Travel: Alaska
create post: invalid character '<' looking for beginning of value
2025/02/20 17:01:51 Creating Book: The Hero With A Thousand Faces
create post: invalid character '<' looking for beginning of value
2025/02/20 17:01:51 Creating So Called 'Mimic Neuron', Scary Implications

THEN

create post: Request: Post "https://write.as/api/collections/mobrec/posts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2025/02/20 17:02:12 Creating Freaking the Tipping Point
create post: Request: Post "https://write.as/api/collections/mobrec/posts": dial tcp [2001:4800:7821:101:be76:4eff:fe04:40a7]:443: connect: connection refused
2025/02/20 17:02:12 Creating Incredible Vanishing Nokia 6682
create post: Request: Post "https://write.as/api/collections/mobrec/posts": dial tcp [2001:4800:7821:101:be76:4eff:fe04:40a7]:443: connect: connection refused
2025/02/20 17:02:12 Creating More On Flock
create post: Request: Post "https://write.as/api/collections/mobrec/posts": dial tcp [2001:4800:7821:101:be76:4eff:fe04:40a7]:443: connect: connection refused
2025/02/20 17:02:13 Creating Video iPod Next Week?

**Comment by thebaer** [comment]
We'll probably need a way to slow down requests and/or add support for an "[Application Key](https://discuss.write.as/t/auth-trouble-with-wp-import-tool/5226/8)" for Write.as in particular. Would you mind opening a new issue for the rate-limiting problem, since this one has been fixed?
